name: CI/CD Pipeline for NGINX Docker Container

on:
  push:
    paths:
      - index.html  # Este pipeline solo se ejecutará cuando el index.html cambie

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Paso 1: Revisar el código del repositorio
    - name: Checkout repository
      uses: actions/checkout@v2

    # Paso 2: Configurar Docker Buildx para usar la caché y optimizar la construcción
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Paso 3: Construir la imagen de Docker
    - name: Build the Docker image
      run: |
        docker build -t my-nginx-image .
    
    # Paso 4: Publicar la imagen en Docker Hub (o cualquier otro registry)
    - name: Push Docker image to Docker Hub
      run: |
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        docker tag my-nginx-image $DOCKER_USERNAME/my-nginx-image:latest
        docker push $DOCKER_USERNAME/my-nginx-image:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
