on:
  push:
    paths:
      - '2-Django-React/frontend/public/index.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Revisar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Paso 3: Construir la imagen de Docker
      - name: Build the Docker image
        run: |
          docker build -f 2-Django-React/frontend/Dockerfile -t my-frontend-image 2-Django-React/
          docker build -f 2-Django-React/backend/Dockerfile -t my-backend-image 2-Django-React/
      
      # Paso 4: Publicar la imagen
      - name: Push Docker image to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker tag my-frontend-image $DOCKER_USERNAME/my-frontend-image:latest
          docker tag my-backend-image $DOCKER_USERNAME/my-backend-image:latest
          docker push $DOCKER_USERNAME/my-frontend-image:latest
          docker push $DOCKER_USERNAME/my-backend-image:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 5: Instalar Azure CLI manualmente
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Paso 6: Autenticarse en Azure
      - name: Authenticate with Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      # Paso 7: Obtener credenciales del cluster de AKS
      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      # Paso 8: Deploy kubernetes
      - name: Deploy to AKS
        env:
          FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-frontend-image:latest
          BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-backend-image:latest
        run: |
          kubectl create namespace django || echo "Namespace already exists"
          sed -i "s|FRONTEND_IMAGE|$FRONTEND_IMAGE|g" 2-Django-React/kubernetes/deployment.yaml
          sed -i "s|BACKEND_IMAGE|$BACKEND_IMAGE|g" 2-Django-React/kubernetes/deployment.yaml
          kubectl apply -f 2-Django-React/kubernetes/deployment.yaml
          kubectl apply -f 2-Django-React/kubernetes/service.yaml
          kubectl rollout restart deployment -n django