name: CI/CD Pipeline for NGINX Docker Container

on:
  push:
    paths:
      - '3-CICD/index.html' # Ruta al archivo específico

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Revisar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Paso 3: Construir la imagen de Docker
      - name: Build the Docker image
        run: |
          docker build -f 3-CICD/Dockerfile -t my-nginx-image 3-CICD/
      
      # Paso 4: Publicar la imagen
      - name: Push Docker image to Docker Hub
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker tag my-nginx-image $DOCKER_USERNAME/my-nginx-image:latest
          docker push $DOCKER_USERNAME/my-nginx-image:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 5: Desplegar la imagen en AWS ECS
      - name: Deploy to AWS ECS
        uses: jakejarvis/ecs-deploy-action@v1
        with:
          cluster: testing  # Nombre del cluster ECS
          service: my-nginx-service # Nombre del servicio ECS
          task-definition: my-nginx-task # Definición de la tarea en ECS
          region: us-east-1         # Región de AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
