name: CI/CD Pipeline for NGINX Docker Container

on:
  push:
    paths:
      - index.html  # Este pipeline solo se ejecutará cuando el index.html cambie

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Revisar el código del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Paso 2: Configurar Docker Buildx (opcional)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Paso 3: Login en Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 4: Construir y publicar la imagen Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-nginx-image:latest
